name: Test MNIST Model

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install torch torchvision

    - name: Run model test
      run: |
        python model.py
    
    - name: Run model with different test data for accr
      run: |
        python test_model.py

    - name: Run model with adam for accr
      run: |
        python test_model_adam_optimizer.py

